#ifndef APP_ERRORS_H
#define APP_ERRORS_H

typedef enum {
    ERROR_BMA_INIT,
    ERROR_BMA_READ_FIFO,
    ERROR_BMA_GET_MAX_ACCEL,
    ERROR_BMA_GET_TEMPERATURE,
    ERROR_EEPROM_INIT,
    ERROR_EEPROM_READ,
    ERROR_EEPROM_WRITE,
    ERROR_RCC_OSC_CONFIG,
    ERROR_RCC_CLOCK_CONFIG,
    ERROR_RTC_INIT,
    ERROR_RTC_SET_ALARM,
    ERROR_RTC_SET_TIMER,
    ERROR_UART_INIT,
    ERROR_I2C_INIT,
    ERROR_DMA_INIT,
    ERROR_TIMER_START,
    ERROR_FLASH_INIT,
    ERROR_SUBGHZ_INIT,
    ERROR_MAX_ACCEL_TOO_HIGH,
    ERROR_MAX_ACCEL_TOO_LOW,
    ERROR_nPM2100_INIT,
    ERROR_nPM2100,
    ERROR_TEST
} ErrorCode_t;

void Error_Handler(ErrorCode_t error_code);

#endif // APP_ERRORS_H